
spring.datasource.url=jdbc:postgresql://localhost:5432/Bus_Mate
spring.datasource.username=postgres
spring.datasource.password=postgreempire3@

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

server.port=8081
spring.app.jwtSecret=${JWT_SECRET_KEY}
spring.app.jwtExpirationMs=9000000
spring.app.jwtRefreshMs=604800000
spring.ecom.app.jwtCookieName=springBootEcom
security.cookie.access-max-age=900
security.cookie.refresh-max-age=604800

#need to set the email and pass in env variable after creating app pass and then use it here like this
collab.admin.email=${YOUR_EMAIL}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${YOUR_EMAIL}
spring.mail.password=${YOUR_EMAIL_PASS}
#so i have to set the pass and email property in env variable after creating App pass and then use it here like this
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#spring.security.user.name=aryan
#spring.security.user.password=aryan@123
#spring.security.user.role=ADMIN
#now they are coming from the database table
